"""004_tg_id_to_bigint

Revision ID: 0d7ac87f86e0
Revises: 5575ce058b0c
Create Date: 2026-01-27 17:46:43.225327

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d7ac87f86e0"
down_revision = "5575ce058b0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tg_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tg_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
