"""008_add_created_at_to_user

Revision ID: 1462faa278a5
Revises: da3b317c14df
Create Date: 2026-02-07 18:10:00.924688

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1462faa278a5"
down_revision = "da3b317c14df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
