"""012_add_amount_to_payment

Revision ID: 146691c1d509
Revises: a8356fc2bc13
Create Date: 2026-02-08 22:18:22.511614

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "146691c1d509"
down_revision = "a8356fc2bc13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("amount", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "amount")
    # ### end Alembic commands ###
