"""013_make_user_id_unique_to_subscription

Revision ID: 1b254e7d2c0a
Revises: 146691c1d509
Create Date: 2026-02-09 21:35:41.243489

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b254e7d2c0a"
down_revision = "146691c1d509"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
