"""002_add_images_file_id

Revision ID: 497e7aa460c8
Revises: 001_initial
Create Date: 2026-01-25 00:52:11.417529

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "497e7aa460c8"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("file_id", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "file_id")
    # ### end Alembic commands ###
