"""003_merge_favourites

Revision ID: 5575ce058b0c
Revises: 497e7aa460c8
Create Date: 2026-01-25 20:29:48.882178

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "5575ce058b0c"
down_revision = "497e7aa460c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем существующий тип contenttype
    contenttype_enum = postgresql.ENUM(
        "THEORY", "QUESTION", "TASK", "SLIDE", name="contenttype", create_type=False
    )

    op.create_table(
        "user_favorites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "content_type",
            contenttype_enum,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "item_id", "content_type", name="uq_user_favorite"
        ),
    )
    op.create_index(
        op.f("ix_user_favorites_content_type"),
        "user_favorites",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_favorites_item_id"), "user_favorites", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_favorites_user_id"), "user_favorites", ["user_id"], unique=False
    )

    # Перенос данных из старых таблиц в новую
    conn = op.get_bind()

    # Перенос из user_favorite_theory
    conn.execute(
        sa.text(
            """
            INSERT INTO user_favorites (user_id, item_id, content_type)
            SELECT user_id, item_id, 'THEORY'::contenttype
            FROM user_favorite_theory
            ON CONFLICT (user_id, item_id, content_type) DO NOTHING
        """
        )
    )

    # Перенос из user_favorite_exam (QUESTION)
    conn.execute(
        sa.text(
            """
            INSERT INTO user_favorites (user_id, item_id, content_type)
            SELECT user_id, item_id, 'QUESTION'::contenttype
            FROM user_favorite_exam
            ON CONFLICT (user_id, item_id, content_type) DO NOTHING
        """
        )
    )

    # Перенос из user_favorite_task
    conn.execute(
        sa.text(
            """
            INSERT INTO user_favorites (user_id, item_id, content_type)
            SELECT user_id, item_id, 'TASK'::contenttype
            FROM user_favorite_task
            ON CONFLICT (user_id, item_id, content_type) DO NOTHING
        """
        )
    )

    op.drop_index(
        op.f("ix_user_favorite_task_item_id"), table_name="user_favorite_task"
    )
    op.drop_index(
        op.f("ix_user_favorite_task_user_id"), table_name="user_favorite_task"
    )
    op.drop_table("user_favorite_task")
    op.drop_index(
        op.f("ix_user_favorite_theory_item_id"), table_name="user_favorite_theory"
    )
    op.drop_index(
        op.f("ix_user_favorite_theory_user_id"), table_name="user_favorite_theory"
    )
    op.drop_table("user_favorite_theory")
    op.drop_index(
        op.f("ix_user_favorite_exam_item_id"), table_name="user_favorite_exam"
    )
    op.drop_index(
        op.f("ix_user_favorite_exam_user_id"), table_name="user_favorite_exam"
    )
    op.drop_table("user_favorite_exam")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorite_exam",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("user_favorite_exam_item_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_favorite_exam_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_favorite_exam_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "item_id",
            name=op.f("uq_user_favorite_exam"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_favorite_exam_user_id"),
        "user_favorite_exam",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_favorite_exam_item_id"),
        "user_favorite_exam",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "user_favorite_theory",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("user_favorite_theory_item_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_favorite_theory_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_favorite_theory_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "item_id",
            name=op.f("uq_user_favorite_theory"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_favorite_theory_user_id"),
        "user_favorite_theory",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_favorite_theory_item_id"),
        "user_favorite_theory",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "user_favorite_task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("user_favorite_task_item_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_favorite_task_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_favorite_task_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "item_id",
            name=op.f("uq_user_favorite_task"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_favorite_task_user_id"),
        "user_favorite_task",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_favorite_task_item_id"),
        "user_favorite_task",
        ["item_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_user_favorites_user_id"), table_name="user_favorites")
    op.drop_index(op.f("ix_user_favorites_item_id"), table_name="user_favorites")
    op.drop_index(op.f("ix_user_favorites_content_type"), table_name="user_favorites")
    op.drop_table("user_favorites")
    # ### end Alembic commands ###
