"""010_refferals

Revision ID: b7ebda023669
Revises: 5b3c63f6716f
Create Date: 2026-02-07 22:40:51.413648

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7ebda023669"
down_revision = "5b3c63f6716f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("referral_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["referral_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "referral_id", name="uq_user_referral"),
    )
    op.create_index(
        op.f("ix_referrals_referral_id"), "referrals", ["referral_id"], unique=True
    )
    op.create_index(
        op.f("ix_referrals_user_id"), "referrals", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referrals_user_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_referral_id"), table_name="referrals")
    op.drop_table("referrals")
    # ### end Alembic commands ###
