"""007_add_is_full_to_item

Revision ID: da3b317c14df
Revises: f41b3fd4ad8f
Create Date: 2026-02-07 00:33:23.063733

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da3b317c14df"
down_revision = "f41b3fd4ad8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column("items", sa.Column("is_full", sa.Boolean(), nullable=True))

    # Устанавливаем значение по умолчанию для всех существующих строк
    op.execute("UPDATE items SET is_full = TRUE WHERE is_full IS NULL")

    # Теперь делаем колонку NOT NULL
    op.alter_column("items", "is_full", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "is_full")
    # ### end Alembic commands ###
