"""006_add_username_to_user

Revision ID: f41b3fd4ad8f
Revises: 005_m2m
Create Date: 2026-02-06 15:34:20.580329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f41b3fd4ad8f"
down_revision = "005_m2m"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
